# modules/data.py
# Static data used across the CFAI Smart Study Planner.

SYLLABUS = {
    "CO1": {
        "title": "Foundations of AI and Python",
        "difficulty": "Medium",
        "importance": "High",
        "topics": [
            "Agent Model and Rational Agents",
            "PEAS Framework",
            "Environment Types",
            "Problem Formulation: State, Action, Transition, Cost",
            "Knowledge Representation: Graphs and Trees",
            "Knowledge Representation: Rule Sets and Constraints",
            "Python: Functions and Recursion",
            "Python: Classes and Dataclasses for State",
            "Python: Typing Hints",
            "Data Structures: dict, set, list",
            "Data Structures: Heaps and Priority Queue",
            "Trace Logging and Step-by-Step Reasoning",
            "Testing Small Algorithm Units",
        ],
    },
    "CO2": {
        "title": "Search Algorithms",
        "difficulty": "Hard",
        "importance": "Very High",
        "topics": [
            "Breadth-First Search (BFS)",
            "Depth-First Search (DFS)",
            "Uniform Cost Search (UCS)",
            "A* Search",
            "Greedy Best-First Search",
            "Heuristic Design and Evaluation",
            "Admissibility and Consistency",
            "Closed and Open Sets",
            "Tie-Breaking Strategies",
            "Memory-Bounded Variants (Concept)",
            "IDA* (Concept Only)",
            "Empirical Profiling: Node Expansions and Runtime",
            "Search on Graphs and Puzzles",
        ],
    },
    "CO3": {
        "title": "Constraint Satisfaction Problems",
        "difficulty": "Hard",
        "importance": "High",
        "topics": [
            "CSP Modeling",
            "Backtracking Search",
            "Constraint Propagation",
            "Forward Checking",
            "Arc Consistency (Intuition)",
            "MRV Heuristic",
            "Degree Heuristic",
            "LCV Heuristic",
            "Local Search for CSP: Min-Conflicts",
            "Scheduling and Timetabling",
            "SAT as Modeling Tool (Intuition)",
            "Explainability for Constraint Failures",
        ],
    },
    "CO4": {
        "title": "Adversarial Search and Decisions",
        "difficulty": "Medium",
        "importance": "High",
        "topics": [
            "Utility Functions",
            "Minimax Algorithm",
            "Alpha-Beta Pruning",
            "Evaluation Functions",
            "Depth Limits in Search",
            "Iterative Deepening (Concept)",
            "Stochastic Decisions Overview",
            "Bounded Rationality",
            "Policy Selection",
            "Multi-Agent Reasoning Basics",
        ],
    },
    "CO5": {
        "title": "Probabilistic Reasoning",
        "difficulty": "Very Hard",
        "importance": "High",
        "topics": [
            "Probability Review",
            "Bayes Rule",
            "Bayesian Networks: Structure",
            "Bayesian Networks: CPT",
            "Variable Elimination",
            "Belief Propagation (Intuition)",
            "Rejection Sampling (Concept)",
            "Likelihood Weighting (Concept)",
            "Markov Chains and HMM (Intuition)",
            "Sensor Fusion Reasoning",
            "Uncertainty-Aware Decisions",
        ],
    },
    "CO6": {
        "title": "Hybrid AI and Exam Readiness",
        "difficulty": "Hard",
        "importance": "Very High",
        "topics": [
            "Combining Search, CSP, and Probabilistic Inference",
            "Hybrid Architecture: Rule + Search + Probabilistic",
            "Explainable Reasoning Traces",
            "Performance Engineering and Failure Analysis",
            "Ethics: Bias in Heuristics",
            "Uncertainty Miscalibration",
            "Preparation for ML and DL",
            "Preparation for NLP and GenAI",
        ],
    },
}

QUIZ_QUESTIONS = {
    "CO1": [
        {
            "q": "What does PEAS stand for in AI agent design?",
            "options": [
                "Performance, Environment, Actuators, Sensors",
                "Program, Execution, Action, State",
                "Problem, Evaluation, Agent, Solution",
                "Process, Environment, Algorithm, Search",
            ],
            "answer": 0,
            "topic": "PEAS Framework",
        },
        {
            "q": "Which of the following is a fully observable environment?",
            "options": ["Poker game", "Chess game", "Partially lit room", "Weather forecasting"],
            "answer": 1,
            "topic": "Environment Types",
        },
        {
            "q": "In problem formulation, the transition model defines:",
            "options": [
                "The start state",
                "The goal state",
                "How actions change states",
                "The cost of each action",
            ],
            "answer": 2,
            "topic": "Problem Formulation: State, Action, Transition, Cost",
        },
        {
            "q": "Which Python data structure gives O(1) average-time lookup by key?",
            "options": ["List", "Dictionary", "Tuple", "Stack"],
            "answer": 1,
            "topic": "Data Structures: dict, set, list",
        },
        {
            "q": "A rational agent acts to:",
            "options": [
                "Always find the globally optimal solution",
                "Maximize its expected performance measure",
                "Never make mistakes",
                "Use machine learning only",
            ],
            "answer": 1,
            "topic": "Agent Model and Rational Agents",
        },
        {
            "q": "Which Python module provides a heap-based priority queue?",
            "options": ["queue", "heapq", "collections", "bisect"],
            "answer": 1,
            "topic": "Data Structures: Heaps and Priority Queue",
        },
    ],
    "CO2": [
        {
            "q": "BFS guarantees the shortest path when:",
            "options": [
                "All edges have equal cost",
                "The graph has no cycles",
                "The heuristic is admissible",
                "The graph is weighted",
            ],
            "answer": 0,
            "topic": "Breadth-First Search (BFS)",
        },
        {
            "q": "DFS uses which data structure internally?",
            "options": ["Queue (FIFO)", "Heap", "Stack (LIFO)", "Deque"],
            "answer": 2,
            "topic": "Depth-First Search (DFS)",
        },
        {
            "q": "A heuristic is admissible if it:",
            "options": [
                "Always overestimates the cost to the goal",
                "Always underestimates (or equals) the real cost",
                "Equals the actual cost exactly",
                "Is always zero",
            ],
            "answer": 1,
            "topic": "Admissibility and Consistency",
        },
        {
            "q": "In A* search, f(n) equals:",
            "options": ["g(n) + h(n)", "h(n) - g(n)", "g(n) × h(n)", "h(n) only"],
            "answer": 0,
            "topic": "A* Search",
        },
        {
            "q": "Greedy Best-First Search selects the next node based on:",
            "options": [
                "g(n) — cumulative path cost",
                "h(n) — estimated cost to goal",
                "f(n) = g(n) + h(n)",
                "Depth of the node",
            ],
            "answer": 1,
            "topic": "Greedy Best-First Search",
        },
        {
            "q": "Which algorithm always expands the node with the lowest cumulative path cost?",
            "options": ["BFS", "DFS", "UCS", "Greedy Search"],
            "answer": 2,
            "topic": "Uniform Cost Search (UCS)",
        },
    ],
    "CO3": [
        {
            "q": "In a CSP, a constraint is:",
            "options": [
                "A time limit on computation",
                "A restriction on which value combinations are valid",
                "A type of search algorithm",
                "A heuristic function",
            ],
            "answer": 1,
            "topic": "CSP Modeling",
        },
        {
            "q": "The MRV heuristic selects the variable with:",
            "options": [
                "The most remaining legal values",
                "The fewest remaining legal values",
                "The highest degree",
                "The largest domain",
            ],
            "answer": 1,
            "topic": "MRV Heuristic",
        },
        {
            "q": "Forward checking removes values that:",
            "options": [
                "Are too large for the variable",
                "Conflict with the current partial assignment for future variables",
                "Are not prime numbers",
                "Violate arc consistency in past variables",
            ],
            "answer": 1,
            "topic": "Forward Checking",
        },
        {
            "q": "Min-Conflicts is classified as:",
            "options": [
                "A complete backtracking search",
                "A local search method for CSP",
                "An uninformed search",
                "An adversarial search",
            ],
            "answer": 1,
            "topic": "Local Search for CSP: Min-Conflicts",
        },
        {
            "q": "Arc consistency (AC-3) ensures that:",
            "options": [
                "All arcs have equal weight",
                "For every value of X, there is a consistent value for Y",
                "No backtracking is ever needed",
                "The CSP has a unique solution",
            ],
            "answer": 1,
            "topic": "Arc Consistency (Intuition)",
        },
        {
            "q": "LCV (Least Constraining Value) prefers the value that:",
            "options": [
                "Rules out the most values in neighboring variables",
                "Rules out the fewest values in neighboring variables",
                "Is the smallest number in the domain",
                "Was assigned first in the domain list",
            ],
            "answer": 1,
            "topic": "LCV Heuristic",
        },
    ],
    "CO4": [
        {
            "q": "In the Minimax algorithm, the MAX player always chooses the move with:",
            "options": [
                "The minimum score",
                "The maximum score",
                "A random score",
                "The average score",
            ],
            "answer": 1,
            "topic": "Minimax Algorithm",
        },
        {
            "q": "Alpha-Beta pruning is designed to:",
            "options": [
                "Speed up Minimax by skipping irrelevant branches",
                "Find the optimal CSP solution",
                "Make BFS use less memory",
                "Train a machine learning model",
            ],
            "answer": 0,
            "topic": "Alpha-Beta Pruning",
        },
        {
            "q": "A utility function in AI represents:",
            "options": [
                "How useful a Python library is",
                "The desirability of a state to an agent",
                "The memory consumed by an algorithm",
                "The processing speed of the CPU",
            ],
            "answer": 1,
            "topic": "Utility Functions",
        },
        {
            "q": "Bounded rationality describes an agent that:",
            "options": [
                "Is always perfectly rational",
                "Makes reasonable decisions given limited time and resources",
                "Has no goals at all",
                "Uses only exact computation",
            ],
            "answer": 1,
            "topic": "Bounded Rationality",
        },
        {
            "q": "An evaluation function in game trees is needed when:",
            "options": [
                "The game tree is fully explored to terminal states",
                "Search is cut off before reaching terminal states",
                "Alpha-Beta pruning is not applied",
                "The game has only one player",
            ],
            "answer": 1,
            "topic": "Evaluation Functions",
        },
        {
            "q": "In a zero-sum two-player game, if one player wins by +5, the other gets:",
            "options": ["+5", "0", "-5", "Unpredictable"],
            "answer": 2,
            "topic": "Minimax Algorithm",
        },
    ],
    "CO5": [
        {
            "q": "Bayes' Rule is primarily used to:",
            "options": [
                "Find the shortest path in a graph",
                "Update the probability of a hypothesis given new evidence",
                "Solve constraint satisfaction problems",
                "Search game trees",
            ],
            "answer": 1,
            "topic": "Bayes Rule",
        },
        {
            "q": "In a Bayesian Network, CPT stands for:",
            "options": [
                "Conditional Probability Table",
                "Complete Path Table",
                "Constraint Propagation Tree",
                "Cost Per Topic",
            ],
            "answer": 0,
            "topic": "Bayesian Networks: CPT",
        },
        {
            "q": "A Hidden Markov Model is best described as:",
            "options": [
                "A graph with weighted edges for shortest paths",
                "A model where true states are hidden and only observations are visible",
                "A technique for solving timetabling CSPs",
                "A game-playing algorithm",
            ],
            "answer": 1,
            "topic": "Markov Chains and HMM (Intuition)",
        },
        {
            "q": "Variable Elimination is a technique for:",
            "options": [
                "Removing columns from a dataset",
                "Exact probabilistic inference in Bayesian Networks",
                "Constraint propagation in CSPs",
                "Reducing the branching factor in BFS",
            ],
            "answer": 1,
            "topic": "Variable Elimination",
        },
        {
            "q": "Rejection Sampling works by:",
            "options": [
                "Removing variables that violate constraints",
                "Generating samples and discarding those inconsistent with evidence",
                "Eliminating variables one by one from a joint distribution",
                "Using backtracking to find consistent assignments",
            ],
            "answer": 1,
            "topic": "Rejection Sampling (Concept)",
        },
        {
            "q": "The notation P(A|B) means:",
            "options": [
                "Probability of A and B both occurring",
                "Probability of A given that B has occurred",
                "Probability of B given that A has occurred",
                "Probability of A or B occurring",
            ],
            "answer": 1,
            "topic": "Bayes Rule",
        },
    ],
    "CO6": [
        {
            "q": "Explainable AI (XAI) matters primarily because:",
            "options": [
                "It makes AI systems run faster",
                "It helps users understand and trust AI decisions",
                "It reduces the memory needed by AI",
                "It removes the need for training data",
            ],
            "answer": 1,
            "topic": "Explainable Reasoning Traces",
        },
        {
            "q": "A hybrid AI system combines:",
            "options": [
                "Only search algorithms",
                "Only probabilistic methods",
                "Multiple techniques like search, CSP, and probabilistic reasoning",
                "Only rule-based expert systems",
            ],
            "answer": 2,
            "topic": "Hybrid Architecture: Rule + Search + Probabilistic",
        },
        {
            "q": "Bias in heuristics can cause:",
            "options": [
                "Faster search times always",
                "Unfair or systematically wrong decisions in AI systems",
                "Always better performance",
                "Simpler, shorter code",
            ],
            "answer": 1,
            "topic": "Ethics: Bias in Heuristics",
        },
        {
            "q": "Uncertainty miscalibration means the AI's:",
            "options": [
                "Code has syntax errors",
                "Confidence values do not match actual probabilities",
                "Model has too many parameters",
                "Search heuristic is inconsistent",
            ],
            "answer": 1,
            "topic": "Uncertainty Miscalibration",
        },
        {
            "q": "CO6's main focus is:",
            "options": [
                "Studying one algorithm deeply",
                "Integrating all CFAI concepts into complete AI systems",
                "Only probabilistic reasoning",
                "Only search algorithms",
            ],
            "answer": 1,
            "topic": "Combining Search, CSP, and Probabilistic Inference",
        },
        {
            "q": "Performance engineering in AI involves:",
            "options": [
                "Only writing faster Python code",
                "Analyzing, measuring, and improving AI systems while identifying failure modes",
                "Using only built-in Python functions",
                "Avoiding recursion in all algorithms",
            ],
            "answer": 1,
            "topic": "Performance Engineering and Failure Analysis",
        },
    ],
}

NOTES = {
    "PEAS": {
        "co": "CO1",
        "definition": "PEAS stands for Performance measure, Environment, Actuators, and Sensors. It is a standard framework for describing what an AI agent is and what it needs to do.",
        "key_points": [
            "Performance measure: How we judge whether the agent is doing well.",
            "Environment: The world the agent operates in (room, road, game board, etc.).",
            "Actuators: The actions the agent can perform (wheels, screen output, etc.).",
            "Sensors: How the agent perceives the world (cameras, keyboards, etc.).",
        ],
        "example": "Self-driving car — Performance: safe driving, obeying laws. Environment: roads, traffic. Actuators: steering, brakes, accelerator. Sensors: cameras, GPS, radar.",
        "exam_hint": "Always write all four components and give a concrete example. Questions may ask you to describe PEAS for a robot, game agent, or medical system.",
    },
    "Problem Formulation": {
        "co": "CO1",
        "definition": "Problem formulation is the process of defining a search problem precisely so an algorithm can solve it. It has five components: initial state, actions, transition model, goal test, and path cost.",
        "key_points": [
            "Initial State: Where the agent starts.",
            "Actions: All possible moves from any state.",
            "Transition Model: What state results from an action in a given state.",
            "Goal Test: A function that checks whether the current state is the goal.",
            "Path Cost: The total cost of the sequence of actions taken.",
        ],
        "example": "8-puzzle: States are board configurations. Actions are tile slides. Goal is the sorted configuration. Cost is the number of moves.",
        "exam_hint": "Be ready to write formal problem formulation for 8-puzzle, route-finding, N-queens, or water-jug problems.",
    },
    "BFS": {
        "co": "CO2",
        "definition": "Breadth-First Search explores nodes level by level, using a queue. It visits all nodes at depth d before visiting any node at depth d+1.",
        "key_points": [
            "Data structure: Queue (FIFO).",
            "Complete: Yes — always finds a solution if one exists in finite graphs.",
            "Optimal: Yes — when all step costs are equal.",
            "Time and space complexity: O(b^d) where b is branching factor, d is depth.",
        ],
        "example": "Finding the shortest number of moves in a maze by exploring all cells at distance 1, then distance 2, and so on.",
        "exam_hint": "BFS is optimal only for unweighted graphs. For weighted graphs, use UCS or A*. BFS uses a lot of memory.",
    },
    "DFS": {
        "co": "CO2",
        "definition": "Depth-First Search explores as far as possible along one path before backtracking. It uses a stack.",
        "key_points": [
            "Data structure: Stack (LIFO).",
            "Complete: No — can get stuck in infinite loops without cycle detection.",
            "Optimal: No — does not guarantee shortest path.",
            "Space complexity: O(bm) — much more memory-efficient than BFS.",
        ],
        "example": "Going down one path of a maze until a dead end, then backtracking to try a different branch.",
        "exam_hint": "DFS uses less memory than BFS but is not guaranteed to find the optimal or even any solution in infinite graphs without visited tracking.",
    },
    "UCS": {
        "co": "CO2",
        "definition": "Uniform Cost Search expands the node with the lowest cumulative path cost. It is essentially Dijkstra's algorithm adapted for AI search.",
        "key_points": [
            "Data structure: Priority queue ordered by path cost g(n).",
            "Complete: Yes.",
            "Optimal: Yes — always finds the least-cost path.",
            "When all costs are equal, UCS behaves like BFS.",
        ],
        "example": "Finding the cheapest bus route between two cities when roads have different ticket prices.",
        "exam_hint": "UCS is optimal because it always expands the cheapest path first. It does not use a heuristic.",
    },
    "A*": {
        "co": "CO2",
        "definition": "A* Search combines the actual path cost g(n) with an estimated cost to the goal h(n). It selects nodes based on f(n) = g(n) + h(n).",
        "key_points": [
            "f(n) = g(n) + h(n).",
            "Optimal and complete if the heuristic is admissible.",
            "Admissible means h(n) never overestimates the real remaining cost.",
            "Consistent (monotone): h(n) ≤ cost(n, a, n') + h(n') for each step.",
        ],
        "example": "GPS navigation: g(n) is the road distance driven so far, h(n) is the straight-line distance to the destination.",
        "exam_hint": "A* is the most important algorithm in CO2. Know f(n) = g(n) + h(n) and what admissibility means. Practice tracing A* on small graphs.",
    },
    "Greedy Search": {
        "co": "CO2",
        "definition": "Greedy Best-First Search selects the node that appears closest to the goal, using only the heuristic h(n). It ignores the path cost so far.",
        "key_points": [
            "Uses only h(n) — no g(n) component.",
            "Not optimal — can find non-shortest paths.",
            "Usually faster than A* but less reliable.",
            "Complete in finite spaces with repeated-state checking.",
        ],
        "example": "Choosing the road that points most directly toward your destination, ignoring road quality or traffic.",
        "exam_hint": "The key exam distinction: Greedy uses h(n) only; A* uses f(n) = g(n) + h(n). Greedy is faster but not optimal.",
    },
    "CSP": {
        "co": "CO3",
        "definition": "A Constraint Satisfaction Problem has three components: variables, domains (possible values), and constraints (rules on valid value combinations).",
        "key_points": [
            "Variables: What needs to be decided/assigned.",
            "Domains: The set of values each variable can take.",
            "Constraints: Rules that must be satisfied by the assignment.",
            "Solution: A complete assignment that satisfies all constraints.",
        ],
        "example": "Map coloring — Variables are regions, domain is {Red, Green, Blue}, constraint is no two adjacent regions can have the same color.",
        "exam_hint": "Know how to model common problems as CSPs: map coloring, N-queens, Sudoku, timetabling. Know the terms variables, domains, and constraints.",
    },
    "MRV": {
        "co": "CO3",
        "definition": "Minimum Remaining Values heuristic selects the variable with the fewest legal values left in its domain for assignment next.",
        "key_points": [
            "Also called the 'fail-first' heuristic.",
            "Helps detect failures early and prune the search space.",
            "It is a variable ordering heuristic (not a value ordering heuristic).",
            "Used inside backtracking search for CSPs.",
        ],
        "example": "In Sudoku, fill the cell that has the fewest possible numbers remaining.",
        "exam_hint": "MRV = fewest remaining values = fail-first. Compare with LCV which is about value ordering.",
    },
    "LCV": {
        "co": "CO3",
        "definition": "Least Constraining Value heuristic selects the value that rules out the fewest choices for neighboring unassigned variables.",
        "key_points": [
            "Value ordering heuristic (contrast: MRV is variable ordering).",
            "Prefers the value that keeps the most options open.",
            "Reduces backtracking by avoiding early domain wipeouts.",
        ],
        "example": "In map coloring, choose the color that does not conflict with the most of the neighbor's remaining values.",
        "exam_hint": "MRV picks which variable to assign next. LCV picks which value to try first. Both are used together in efficient CSP solvers.",
    },
    "Minimax": {
        "co": "CO4",
        "definition": "Minimax is an algorithm for two-player zero-sum games. The MAX player tries to maximize the score; the MIN player tries to minimize it. They alternate turns.",
        "key_points": [
            "MAX player: picks move with the highest value.",
            "MIN player: picks move with the lowest value.",
            "Recursively evaluates the entire game tree.",
            "Terminal states have utility values (e.g., +1, -1, 0).",
        ],
        "example": "Tic-Tac-Toe: X (MAX) wants to maximize utility. O (MIN) wants to minimize it. Minimax finds the best strategy for both.",
        "exam_hint": "Draw and trace a small game tree. Know that MAX and MIN players alternate, and terminal nodes have utilities.",
    },
    "Alpha-Beta Pruning": {
        "co": "CO4",
        "definition": "Alpha-Beta Pruning is an optimization of Minimax that skips (prunes) branches that cannot influence the final decision, without changing the result.",
        "key_points": [
            "Alpha (α): best value MAX can guarantee so far.",
            "Beta (β): best value MIN can guarantee so far.",
            "Prune a branch when α ≥ β.",
            "Gives the same result as Minimax, just faster.",
        ],
        "example": "If MAX already found a guaranteed value of 5, any MIN node that goes below 5 can be ignored — MAX would never choose it.",
        "exam_hint": "Alpha-beta produces identical results to Minimax. It just avoids evaluating branches that cannot change the outcome. Know α and β update rules.",
    },
    "Bayes Rule": {
        "co": "CO5",
        "definition": "Bayes' Rule is a formula to update the probability of a hypothesis H given new evidence E: P(H|E) = P(E|H) × P(H) / P(E).",
        "key_points": [
            "P(H|E): posterior — what we want to know.",
            "P(E|H): likelihood — how probable is the evidence if H is true.",
            "P(H): prior — our belief before seeing evidence.",
            "P(E): marginal — total probability of seeing the evidence.",
        ],
        "example": "Medical diagnosis: P(Disease | Positive Test) = P(Positive Test | Disease) × P(Disease) / P(Positive Test).",
        "exam_hint": "Write the formula and identify all four terms. Practice computing with numbers. This is heavily tested in CO5.",
    },
    "Bayesian Networks": {
        "co": "CO5",
        "definition": "A Bayesian Network is a Directed Acyclic Graph (DAG) where nodes are random variables and edges show conditional dependencies. Each node has a CPT.",
        "key_points": [
            "Nodes represent random variables.",
            "Directed edges show causal or conditional dependence.",
            "CPT (Conditional Probability Table) stores P(node | parents).",
            "Allows compact representation of a large joint distribution.",
        ],
        "example": "Rain → Sprinkler → Wet Grass. Knowing it rains affects whether the sprinkler is on, which affects whether the grass is wet.",
        "exam_hint": "Know how to read a CPT and compute probabilities from a small Bayesian Network. Variable elimination is the main inference method.",
    },
    "HMM": {
        "co": "CO5",
        "definition": "A Hidden Markov Model has hidden states (which we cannot observe directly) and observable outputs. We use observations to infer the hidden states.",
        "key_points": [
            "Hidden states: the true underlying state we want to know.",
            "Observations: what we can actually measure.",
            "Transition probabilities: how states change over time.",
            "Emission probabilities: probability of an observation given a state.",
        ],
        "example": "Weather (hidden: Sunny/Rainy) affects umbrella usage (observable). We see umbrellas and try to infer the weather.",
        "exam_hint": "Key distinction: states are hidden, observations are visible. HMM is used for speech recognition, tracking, and part-of-speech tagging.",
    },
    "Explainable AI": {
        "co": "CO6",
        "definition": "Explainable AI (XAI) refers to AI systems that can clearly explain their reasoning and decisions in terms humans can understand.",
        "key_points": [
            "Transparency: the system shows how a decision was reached.",
            "Trust: users trust systems they understand.",
            "Accountability: critical in medical, legal, and financial domains.",
            "Contrasts with black-box models that give outputs without explanations.",
        ],
        "example": "Loan rejection system that says 'Rejected: income below threshold AND credit score below 650' — this is explainable.",
        "exam_hint": "XAI is both a technical goal and an ethical requirement. Know why it matters and give an example of an explainable decision trace.",
    },
    "Hybrid AI": {
        "co": "CO6",
        "definition": "A Hybrid AI system combines multiple AI paradigms — such as rule-based reasoning, search algorithms, and probabilistic methods — to handle complex real-world problems.",
        "key_points": [
            "Uses the strengths of each AI method together.",
            "Example: rules for obvious cases + Bayesian network for uncertainty + search for planning.",
            "More robust and explainable than single-method systems.",
            "CO6 is about designing and understanding such combined systems.",
        ],
        "example": "A medical diagnosis system: rules for obvious symptoms, Bayesian networks for uncertain evidence, A* search for treatment planning.",
        "exam_hint": "CO6 is about integration. Be ready to sketch a simple hybrid AI architecture combining at least two CFAI techniques with justification.",
    },
}

GRAPH = {
    "A": {"B": 1, "C": 4},
    "B": {"A": 1, "D": 2, "E": 5},
    "C": {"A": 4, "F": 3},
    "D": {"B": 2, "G": 3},
    "E": {"B": 5, "G": 1},
    "F": {"C": 3, "G": 2},
    "G": {"D": 3, "E": 1, "F": 2},
}

HEURISTICS = {"A": 6, "B": 4, "C": 5, "D": 2, "E": 1, "F": 3, "G": 0}

GRAPH_NODES = list(GRAPH.keys())

NODE_POS = {
    "A": (0.0, 2.0),
    "B": (1.2, 3.2),
    "C": (1.2, 0.8),
    "D": (2.5, 3.8),
    "E": (2.5, 2.6),
    "F": (2.5, 0.4),
    "G": (3.8, 2.0),
}

